#!/bin/python3.6


def main():
    input("Press Enter to continue...")
    print()
    print("Create three sets.")
    input()
    print("s1 = set(['cat', 'dog'])")
    print("s2 = set(['dog', 'mouse'])")
    print("s3 = s1 & s2")
    input()
    print("Intersection.")
    input()
    print("s1 & s2")
    input()
    print("Union.")
    input()
    print("s1 | s2")
    input()
    print("Difference.")
    input()
    print("s1 - s3")
    input()
    print("Symmetric Difference.")
    input()
    print("s1 ^ s2")
    input()
    print("issubset")
    input()
    print("s3 < s1")
    input()
    print("issupperset")
    input()
    print("s1 > s3")
    input()
    print("isdisjoint")
    input()
    print("s5 = set(['bird', 'fish'])")
    print("s1.isdisjoint(s5)")
    print()
    input()


if __name__ == '__main__':
    main()
